// Every Huudis feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 111 feature routes of the Huudis API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** List audit (GET /api/v1/account/audit) */
  accountAudit(input?: { "limit"?: number; "cursor"?: string; "event"?: string; "outcome"?: "success" | "failure" | "denied"; "since"?: string; "until"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["event"] = all["event"]; delete all["event"];
    query["outcome"] = all["outcome"]; delete all["outcome"];
    query["since"] = all["since"]; delete all["since"];
    query["until"] = all["until"]; delete all["until"];
    return this.call("GET", `/api/v1/account/audit`, query, undefined);
  }

  /** /billing surface for the Huudis dashboard. (GET /api/v1/account/billing) */
  accountBilling(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/billing`, {}, undefined);
  }

  /** Create a cancel (POST /api/v1/account/billing/cancel) */
  accountBillingCancel(): Promise<unknown> {
    return this.call("POST", `/api/v1/account/billing/cancel`, {}, undefined);
  }

  /** Create a checkout (POST /api/v1/account/billing/checkout) */
  accountBillingCheckout(input: { "tier": "pro" | "business" | "scale"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/billing/checkout`, query, all);
  }

  /** List invoices (GET /api/v1/account/billing/invoices) */
  accountBillingInvoices(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/billing/invoices`, {}, undefined);
  }

  /** Public to authenticated sessions — no account scope needed since every user sees the same plans. (GET /api/v1/account/billing/plans) */
  accountBillingPlans(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/billing/plans`, {}, undefined);
  }

  /** List usage (GET /api/v1/account/billing/usage) */
  accountBillingUsage(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/billing/usage`, {}, undefined);
  }

  /** Create a cancel deletion (POST /api/v1/account/cancel-deletion) */
  accountCancelDeletion(): Promise<unknown> {
    return this.call("POST", `/api/v1/account/cancel-deletion`, {}, undefined);
  }

  /** Signal = `RefreshToken`, not `OidcConsent`. (GET /api/v1/account/connected-apps) */
  accountConnectedApps(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/connected-apps`, {}, undefined);
  }

  /** Revoke every live refresh-token family this user holds for the client. (POST /api/v1/account/connected-apps/{clientId}/revoke) */
  accountConnectedAppsRevoke(clientId: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/connected-apps/${encodeURIComponent(clientId)}/revoke`, {}, undefined);
  }

  /** Create a webhook subscription (POST /api/v1/account/webhook-subscriptions) */
  accountCreateWebhookSubscriptions(input: { "url": string; "events": unknown[]; "description"?: string; "active"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/webhook-subscriptions`, query, all);
  }

  /** Create a workspace (POST /api/v1/account/workspaces) */
  accountCreateWorkspaces(input: { "name": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/workspaces`, query, all);
  }

  /** Delete account (DELETE /api/v1/account) */
  accountDelete(input?: { "password"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("DELETE", `/api/v1/account`, query, all);
  }

  /** Legacy consent-id path. (DELETE /api/v1/account/connected-apps/{id}) */
  accountDeleteConnectedApps(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/account/connected-apps/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a linked account (DELETE /api/v1/account/linked-accounts/{provider}) */
  accountDeleteLinkedAccounts(provider: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/account/linked-accounts/${encodeURIComponent(provider)}`, {}, undefined);
  }

  /** Delete a social provider (DELETE /api/v1/account/social-providers/{provider}) */
  accountDeleteSocialProviders(provider: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/account/social-providers/${encodeURIComponent(provider)}`, {}, undefined);
  }

  /** Delete a webhook subscription (DELETE /api/v1/account/webhook-subscriptions/{id}) */
  accountDeleteWebhookSubscriptions(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/account/webhook-subscriptions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Create an email change (POST /api/v1/account/email-change) */
  accountEmailChange(input: { "email": string; "password": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/email-change`, query, all);
  }

  /** List linked accounts (GET /api/v1/account/linked-accounts) */
  accountLinkedAccounts(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/linked-accounts`, {}, undefined);
  }

  /** List account (GET /api/v1/account) */
  accountList(): Promise<unknown> {
    return this.call("GET", `/api/v1/account`, {}, undefined);
  }

  /** Create a password change (POST /api/v1/account/password-change) */
  accountPasswordChange(input: { "currentPassword"?: string; "newPassword": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/password-change`, query, all);
  }

  /** Self-serve soft-delete: stamps a 30-day grace marker. (POST /api/v1/account/schedule-deletion) */
  accountScheduleDeletion(input?: { "password"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/schedule-deletion`, query, all);
  }

  /** List services (GET /api/v1/account/services) */
  accountServices(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/services`, {}, undefined);
  }

  /** Create a disable (POST /api/v1/account/services/disable) */
  accountServicesDisable(input: { "services": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/services/disable`, query, all);
  }

  /** Create an enable (POST /api/v1/account/services/enable) */
  accountServicesEnable(input: { "services": unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/account/services/enable`, query, all);
  }

  /** List sessions (GET /api/v1/account/sessions) */
  accountSessions(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/sessions`, {}, undefined);
  }

  /** Revoke a session (POST /api/v1/account/sessions/{id}/revoke) */
  accountSessionsRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/sessions/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** Create a revoke all (POST /api/v1/account/sessions/revoke-all) */
  accountSessionsRevokeAll(): Promise<unknown> {
    return this.call("POST", `/api/v1/account/sessions/revoke-all`, {}, undefined);
  }

  /** Replace a social provider (PUT /api/v1/account/social-providers/{provider}) */
  accountSetSocialProviders(provider: string, input: { "clientId": string; "secret"?: string; "redirectUri"?: string; "teamId"?: string; "keyId"?: string; "enabled"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/account/social-providers/${encodeURIComponent(provider)}`, query, all);
  }

  /** List social providers (GET /api/v1/account/social-providers) */
  accountSocialProviders(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/social-providers`, {}, undefined);
  }

  /** Update account (PATCH /api/v1/account) */
  accountUpdate(input?: { "name"?: string; "locale"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/account`, query, all);
  }

  /** Update a webhook subscription (PATCH /api/v1/account/webhook-subscriptions/{id}) */
  accountUpdateWebhookSubscriptions(id: string, input?: { "url"?: string; "events"?: unknown[]; "description"?: string; "active"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/account/webhook-subscriptions/${encodeURIComponent(id)}`, query, all);
  }

  /** Update a workspace (PATCH /api/v1/account/workspaces/{id}) */
  accountUpdateWorkspaces(id: string, input: { "name": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/account/workspaces/${encodeURIComponent(id)}`, query, all);
  }

  /** List webhook subscriptions (GET /api/v1/account/webhook-subscriptions) */
  accountWebhookSubscriptions(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/webhook-subscriptions`, {}, undefined);
  }

  /** Get a webhook subscription (GET /api/v1/account/webhook-subscriptions/{id}) */
  accountWebhookSubscriptions2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/account/webhook-subscriptions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List deliveries (GET /api/v1/account/webhook-subscriptions/{id}/deliveries) */
  accountWebhookSubscriptionsDeliveries(id: string, input?: { "limit"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/account/webhook-subscriptions/${encodeURIComponent(id)}/deliveries`, query, undefined);
  }

  /** Replay a delivery (POST /api/v1/account/webhook-subscriptions/deliveries/{id}/replay) */
  accountWebhookSubscriptionsDeliveriesReplay(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/webhook-subscriptions/deliveries/${encodeURIComponent(id)}/replay`, {}, undefined);
  }

  /** List catalog (GET /api/v1/account/webhook-subscriptions/events/catalog) */
  accountWebhookSubscriptionsEventsCatalog(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/webhook-subscriptions/events/catalog`, {}, undefined);
  }

  /** Rotate secret a webhook subscription (POST /api/v1/account/webhook-subscriptions/{id}/rotate-secret) */
  accountWebhookSubscriptionsRotateSecret(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/webhook-subscriptions/${encodeURIComponent(id)}/rotate-secret`, {}, undefined);
  }

  /** List workspaces (GET /api/v1/account/workspaces) */
  accountWorkspaces(): Promise<unknown> {
    return this.call("GET", `/api/v1/account/workspaces`, {}, undefined);
  }

  /** Cancel deletion a workspace (POST /api/v1/account/workspaces/{id}/cancel-deletion) */
  accountWorkspacesCancelDeletion(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/workspaces/${encodeURIComponent(id)}/cancel-deletion`, {}, undefined);
  }

  /** Additive, read-only. (GET /api/v1/account/workspaces/{id}/members) */
  accountWorkspacesMembers(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/account/workspaces/${encodeURIComponent(id)}/members`, {}, undefined);
  }

  /** Owner-only soft-delete: stamps a 30-day grace marker on the workspace. (POST /api/v1/account/workspaces/{id}/schedule-deletion) */
  accountWorkspacesScheduleDeletion(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/workspaces/${encodeURIComponent(id)}/schedule-deletion`, {}, undefined);
  }

  /** Switch a workspace (POST /api/v1/account/workspaces/{id}/switch) */
  accountWorkspacesSwitch(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/account/workspaces/${encodeURIComponent(id)}/switch`, {}, undefined);
  }

  /** One row per OIDC client that has ever minted a refresh token: distinct users, 30-day signups, last signup + last activity. (GET /api/v1/app/overview) */
  appOverview(): Promise<unknown> {
    return this.call("GET", `/api/v1/app/overview`, {}, undefined);
  }

  /** List stats (GET /api/v1/app/stats) */
  appStats(input?: { "q"?: string; "status"?: "all" | "active" | "disabled"; "limit"?: number; "clientId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["q"] = all["q"]; delete all["q"];
    query["status"] = all["status"]; delete all["status"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["clientId"] = all["clientId"]; delete all["clientId"];
    return this.call("GET", `/api/v1/app/stats`, query, undefined);
  }

  /** List users (GET /api/v1/app/users) */
  appUsers(input?: { "q"?: string; "status"?: "all" | "active" | "disabled"; "limit"?: number; "clientId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["q"] = all["q"]; delete all["q"];
    query["status"] = all["status"]; delete all["status"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["clientId"] = all["clientId"]; delete all["clientId"];
    return this.call("GET", `/api/v1/app/users`, query, undefined);
  }

  /** List workspaces (GET /api/v1/app/workspaces) */
  appWorkspaces(input: { "ids": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["ids"] = all["ids"]; delete all["ids"];
    return this.call("GET", `/api/v1/app/workspaces`, query, undefined);
  }

  /** Create an assume role (POST /api/v1/authz/assume-role) */
  authzAssumeRole(input: { "roleId": string; "sessionName"?: string; "durationSeconds"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/authz/assume-role`, query, all);
  }

  /** Create a check (POST /api/v1/authz/check) */
  authzCheck(input: { "principal": Record<string, unknown>; "action": string; "resource": string; "context"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/authz/check`, query, all);
  }

  /** Session-auth health ping so dashboard can verify reachability. (GET /api/v1/authz/whoami) */
  authzWhoami(): Promise<unknown> {
    return this.call("GET", `/api/v1/authz/whoami`, {}, undefined);
  }

  /** List access keys (GET /api/v1/iam/access-keys) */
  iamAccessKeys(input: { "principalType": "user" | "service_account"; "principalId": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["principalType"] = all["principalType"]; delete all["principalType"];
    query["principalId"] = all["principalId"]; delete all["principalId"];
    return this.call("GET", `/api/v1/iam/access-keys`, query, undefined);
  }

  /** Revoke an access key (POST /api/v1/iam/access-keys/{id}/revoke) */
  iamAccessKeysRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/iam/access-keys/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** List assumed sessions (GET /api/v1/iam/assumed-sessions) */
  iamAssumedSessions(): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/assumed-sessions`, {}, undefined);
  }

  /** Revoke an assumed session (POST /api/v1/iam/assumed-sessions/{id}/revoke) */
  iamAssumedSessionsRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/iam/assumed-sessions/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** Create an access key (POST /api/v1/iam/access-keys) */
  iamCreateAccessKeys(input: { "principalType": "user" | "service_account"; "principalId": string; "label"?: string; "expiresAt"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/access-keys`, query, all);
  }

  /** Create a group (POST /api/v1/iam/groups) */
  iamCreateGroups(input: { "name": string; "description"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/groups`, query, all);
  }

  /** Members a group (POST /api/v1/iam/groups/{id}/members) */
  iamCreateGroupsMembers(id: string, input: { "userId": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/groups/${encodeURIComponent(id)}/members`, query, all);
  }

  /** Create an identity provider (POST /api/v1/iam/identity-providers) */
  iamCreateIdentityProviders(input: { "name": string; "type": "saml" | "oidc"; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/identity-providers`, query, all);
  }

  /** Create an invite (POST /api/v1/iam/invites) */
  iamCreateInvites(input: { "email": string; "role"?: "owner" | "admin" | "member"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/invites`, query, all);
  }

  /** Create a policy (POST /api/v1/iam/policies) */
  iamCreatePolicies(input: { "name": string; "description"?: string; "document": Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/policies`, query, all);
  }

  /** Create a policy attachment (POST /api/v1/iam/policy-attachments) */
  iamCreatePolicyAttachments(input: { "policyId": string; "principalType": "user" | "group" | "role" | "service_account"; "principalId": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/policy-attachments`, query, all);
  }

  /** Create a role (POST /api/v1/iam/roles) */
  iamCreateRoles(input: { "name": string; "description"?: string; "trustPolicy": Record<string, unknown>; "maxSessionDurationSec"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/roles`, query, all);
  }

  /** Create a service account (POST /api/v1/iam/service-accounts) */
  iamCreateServiceAccounts(input: { "name": string; "description"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/service-accounts`, query, all);
  }

  /** Create an user (POST /api/v1/iam/users) */
  iamCreateUsers(input: { "email": string; "name"?: string; "password"?: string; "role"?: "owner" | "admin" | "member"; "emailVerified"?: boolean; "sendInviteEmail"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/iam/users`, query, all);
  }

  /** Delete an access key (DELETE /api/v1/iam/access-keys/{id}) */
  iamDeleteAccessKeys(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/access-keys/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a group (DELETE /api/v1/iam/groups/{id}) */
  iamDeleteGroups(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/groups/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a member (DELETE /api/v1/iam/groups/{id}/members/{userId}) */
  iamDeleteGroupsMembers(id: string, userId: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/groups/${encodeURIComponent(id)}/members/${encodeURIComponent(userId)}`, {}, undefined);
  }

  /** Delete an identity provider (DELETE /api/v1/iam/identity-providers/{id}) */
  iamDeleteIdentityProviders(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/identity-providers/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete an invite (DELETE /api/v1/iam/invites/{id}) */
  iamDeleteInvites(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/invites/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a policy (DELETE /api/v1/iam/policies/{id}) */
  iamDeletePolicies(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/policies/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a policy attachment (DELETE /api/v1/iam/policy-attachments/{id}) */
  iamDeletePolicyAttachments(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/policy-attachments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a role (DELETE /api/v1/iam/roles/{id}) */
  iamDeleteRoles(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/roles/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a service account (DELETE /api/v1/iam/service-accounts/{id}) */
  iamDeleteServiceAccounts(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/service-accounts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete an user (DELETE /api/v1/iam/users/{id}) */
  iamDeleteUsers(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/iam/users/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List groups (GET /api/v1/iam/groups) */
  iamGroups(): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/groups`, {}, undefined);
  }

  /** Get a group (GET /api/v1/iam/groups/{id}) */
  iamGroups2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/groups/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List identity providers (GET /api/v1/iam/identity-providers) */
  iamIdentityProviders(): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/identity-providers`, {}, undefined);
  }

  /** List invites (GET /api/v1/iam/invites) */
  iamInvites(): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/invites`, {}, undefined);
  }

  /** List policies (GET /api/v1/iam/policies) */
  iamPolicies(): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/policies`, {}, undefined);
  }

  /** Get a policy (GET /api/v1/iam/policies/{id}) */
  iamPolicies2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/policies/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List policy attachments (GET /api/v1/iam/policy-attachments) */
  iamPolicyAttachments(input?: { "policyId"?: string; "principalType"?: "user" | "group" | "role" | "service_account"; "principalId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["policyId"] = all["policyId"]; delete all["policyId"];
    query["principalType"] = all["principalType"]; delete all["principalType"];
    query["principalId"] = all["principalId"]; delete all["principalId"];
    return this.call("GET", `/api/v1/iam/policy-attachments`, query, undefined);
  }

  /** List roles (GET /api/v1/iam/roles) */
  iamRoles(): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/roles`, {}, undefined);
  }

  /** Get a role (GET /api/v1/iam/roles/{id}) */
  iamRoles2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/roles/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List service accounts (GET /api/v1/iam/service-accounts) */
  iamServiceAccounts(): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/service-accounts`, {}, undefined);
  }

  /** Get a service account (GET /api/v1/iam/service-accounts/{id}) */
  iamServiceAccounts2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/service-accounts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Update an identity provider (PATCH /api/v1/iam/identity-providers/{id}) */
  iamUpdateIdentityProviders(id: string, input?: { "name"?: string; "metadata"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/iam/identity-providers/${encodeURIComponent(id)}`, query, all);
  }

  /** Update a policy (PATCH /api/v1/iam/policies/{id}) */
  iamUpdatePolicies(id: string, input?: { "description"?: string; "document"?: Record<string, unknown>; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/iam/policies/${encodeURIComponent(id)}`, query, all);
  }

  /** Update an user (PATCH /api/v1/iam/users/{id}) */
  iamUpdateUsers(id: string, input?: { "role"?: "owner" | "admin" | "member"; "emailVerified"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/iam/users/${encodeURIComponent(id)}`, query, all);
  }

  /** List users (GET /api/v1/iam/users) */
  iamUsers(): Promise<unknown> {
    return this.call("GET", `/api/v1/iam/users`, {}, undefined);
  }

  /** Reset password an user (POST /api/v1/iam/users/{id}/reset-password) */
  iamUsersResetPassword(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/iam/users/${encodeURIComponent(id)}/reset-password`, {}, undefined);
  }

  /** Read-only — lets the standalone /mfa page render the right input (authenticator vs. emailed code) regardless of which flow created the challenge. (GET /api/v1/mfa/challenge) */
  mfaChallenge(input?: { "token"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["token"] = all["token"]; delete all["token"];
    return this.call("GET", `/api/v1/mfa/challenge`, query, undefined);
  }

  /** Delete a device (DELETE /api/v1/mfa/devices/{id}) */
  mfaDeleteDevices(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/mfa/devices/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List devices (GET /api/v1/mfa/devices) */
  mfaDevices(): Promise<unknown> {
    return this.call("GET", `/api/v1/mfa/devices`, {}, undefined);
  }

  /** Create an enroll (POST /api/v1/mfa/enroll) */
  mfaEnroll(input?: { "method"?: "totp" | "email"; "label"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/mfa/enroll`, query, all);
  }

  /** Create a resend code (POST /api/v1/mfa/resend-code) */
  mfaResendCode(input: { "mfaChallengeToken": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/mfa/resend-code`, query, all);
  }

  /** Create a resend enrollment code (POST /api/v1/mfa/resend-enrollment-code) */
  mfaResendEnrollmentCode(input: { "deviceId": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/mfa/resend-enrollment-code`, query, all);
  }

  /** Create a verify enrollment (POST /api/v1/mfa/verify-enrollment) */
  mfaVerifyEnrollment(input: { "deviceId": string; "code"?: string; "totpCode"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/mfa/verify-enrollment`, query, all);
  }

  /** Create a verify login (POST /api/v1/mfa/verify-login) */
  mfaVerifyLogin(input: { "mfaChallengeToken": string; "code": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/mfa/verify-login`, query, all);
  }

  /** List clients (GET /api/v1/oidc/clients) */
  oidcClients(): Promise<unknown> {
    return this.call("GET", `/api/v1/oidc/clients`, {}, undefined);
  }

  /** Rotate secret a client (POST /api/v1/oidc/clients/{id}/rotate-secret) */
  oidcClientsRotateSecret(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/oidc/clients/${encodeURIComponent(id)}/rotate-secret`, {}, undefined);
  }

  /** Create a client (POST /api/v1/oidc/clients) */
  oidcCreateClients(input: { "name": string; "redirectUris"?: unknown[]; "scopes"?: unknown[]; "public"?: boolean; "logoUrl"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/oidc/clients`, query, all);
  }

  /** Delete a client (DELETE /api/v1/oidc/clients/{id}) */
  oidcDeleteClients(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/oidc/clients/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Update a client (PATCH /api/v1/oidc/clients/{id}) */
  oidcUpdateClients(id: string, input?: { "name"?: string; "redirectUris"?: unknown[]; "scopes"?: unknown[]; "logoUrl"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/oidc/clients/${encodeURIComponent(id)}`, query, all);
  }

  /** Workspace-scoped directory of end-users — people who have consented to an OIDC client owned by the active workspace. (GET /api/v1/ops/end-users) */
  opsEndUsers(): Promise<unknown> {
    return this.call("GET", `/api/v1/ops/end-users`, {}, undefined);
  }

  /** Get an end user (GET /api/v1/ops/end-users/{id}) */
  opsEndUsers2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/ops/end-users/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Impersonate an end user (POST /api/v1/ops/end-users/{id}/impersonate) */
  opsEndUsersImpersonate(id: string, input?: { "durationSeconds"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/ops/end-users/${encodeURIComponent(id)}/impersonate`, query, all);
  }

  /** Revoke an end user (POST /api/v1/ops/end-users/{id}/revoke) */
  opsEndUsersRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/ops/end-users/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** Send password reset an end user (POST /api/v1/ops/end-users/{id}/send-password-reset) */
  opsEndUsersSendPasswordReset(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/ops/end-users/${encodeURIComponent(id)}/send-password-reset`, {}, undefined);
  }

  /** Create a stop impersonation (POST /api/v1/ops/end-users/stop-impersonation) */
  opsEndUsersStopImpersonation(): Promise<unknown> {
    return this.call("POST", `/api/v1/ops/end-users/stop-impersonation`, {}, undefined);
  }

  /** Verify email an end user (POST /api/v1/ops/end-users/{id}/verify-email) */
  opsEndUsersVerifyEmail(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/ops/end-users/${encodeURIComponent(id)}/verify-email`, {}, undefined);
  }
}
